### ISSUE TITLE
Add help documentation

### ISSUE THREAD

**Issue by AugustT** [NERC-CEH/e-surveyor-app#104]
The demonstration version of the app has no documentation. In this phase we want to add extensive documentation for all of hte features of the app.

"_Testing of the first version of the app has highlighted the features that users find intuitive and those that need greater explanation. We will implement user-interface improvement where they are feasible but meeting usability requirements for all potential users of the app is not feasible.  We will therefore develop explainer notifications and help pages to support users as they become familiar with the app. This will include a help page on each of the main features of the app, on how to take a good image for the AI classifier and explainers on the reports that the app creates.  We will also produce videos demonstrating the use of the app (e.g. to support ELM user stories).  Feedback from user shows that the diversity of participants (from tech-savvy to less experienced users) suggests that multiple route to providing of help and guidance is needed to engage a wide user community_"

- [x] Create an FAQ page
- [x] Create help documentation for how to take a good image (see NERC-CEH/e-surveyor-app#79)
- [x] Create help documentation for the ID a plant page
- [x] Create help documentation for Habitat survey page
- [x] Create help documentation for the transect page (see NERC-CEH/e-surveyor-app#75 and NERC-CEH/e-surveyor-app#72 and NERC-CEH/e-surveyor-app#12)
- [ ] Add links out to video tutorials (maybe cut up this: https://www.youtube.com/watch?v=XcYGKJZH7-o)
- [ ] Explain the report pages (see NERC-CEH/e-surveyor-app#81 and NERC-CEH/e-surveyor-app#64)
- [x] Add help doc for the tree survey feature (#102) once it is added 

Some of this help documentation might pop up the first time the user visits a certain page, some might be accessible through help buttons, and some might be a page tour, highlighting features on the page, rather than a traditional help page

To involve @robin-hutchinson in the new year
